
- name: Deploy spring application
  hosts: web
  become: true
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
         update_cache: yes
    - name: Install Mysql on Debian
      ansible.builtin.apt:
         name: mysql-server
         state: present
      when: ansible_os_family == "Debian"
 
    - name: Install java 11 on Debian
      ansible.builtin.apt:
         name: openjdk-11-jdk
         state: present
      when: ansible_os_family == "Debian"

    - name: Install Maven
      apt:
         name: maven
         state: present

    - name: Download Apache Tomcat
      get_url:
         url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.96/bin/apache-tomcat-9.0.96.tar.gz
         dest: /tmp/apache-tomcat-9.0.96.tar.gz

    - name: Extract Tomcat
      unarchive:
         src: /tmp/apache-tomcat-9.0.96.tar.gz
         dest: /opt
         remote_src: yes

    - name: Clone the Spring3Hibernate repository
      git:
         repo: https://github.com/opstree/spring3hibernate.git
         dest: /opt/spring3hibernate
         version: master

    - name: Create WAR file using Maven
      command: mvn clean package
      args:
         chdir: /opt/spring3hibernate
  

    - name: Copy WAR file to Tomcat webapps directory
      copy:
         src: /opt/spring3hibernate/target/Spring3HibernateApp.war
         dest: /opt/apache-tomcat-9.0.96/webapps/
         remote_src: yes


    - name: Add roles and user to tomcat-users.xml
      ansible.builtin.blockinfile:
        path: /opt/apache-tomcat-9.0.96/conf/tomcat-users.xml
        block: |
          <role rolename="manager-gui"/>
          <role rolename="manager-script"/>
          <user username="tomcat" password="tomcat" roles="manager-gui,manager-script"/>
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"    
        
    - name: Remove RemoteAddrValve line from server.xml
      ansible.builtin.lineinfile:
        path: /path/to/your/server.xml  # Replace with the actual file path
        state: absent
        regexp: '<Valve className="org.apache.catalina.valves.RemoteAddrValve"\s*allow="127\\.\d+\\.\d+\\.\d+\|::1\|0:0:0:0:0:0:0:1" />'
        
    - name: Stop Tomcat
      ansible.builtin.command: /opt/apache-tomcat-9.0.96/bin/shutdown.sh
      ignore_errors: yes

    - name: Start Tomcat
      ansible.builtin.command: /opt/apache-tomcat-9.0.96/bin/startup.sh

